apiVersion: v1
kind: Secret
metadata:
  name: github-actions-deployer-token
  namespace: diplom-app
  annotations:
    kubernetes.io/service-account.name: github-actions-deployer
type: kubernetes.io/service-account-token