apiVersion: v1
kind: Secret
metadata:
  name: atlantis-vcs
  namespace: atlantis
type: Opaque
stringData:
  ATLANTIS_GH_USER: "github-username"
  ATLANTIS_GH_TOKEN: "github-token"
  ATLANTIS_GH_WEBHOOK_SECRET: "webhook-secret"